meta:
  id: unknown_data50
  endian: le
  imports:
    - smart_types

seq:
  # - size: 0x8dfc4

  - type: smart_types::nulls(4)

  - type: u1
    valid: 4

  - id: num_records_4
    type: u4

  - type: smart_types::nulls(4)

  - id: net_exe_pou_name
    type: smart_types::strl
    # NET_EXE is generated by the network wizard
    # it handles GET/PUT sequences

  - size: 22
